env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent:
    - "error"
    - 2
    - { MemberExpression: "off", SwitchCase: 1 }
  quotes:
    - "error"
    - "double"
  semi:
    - "error"
    - "always"
  func-style:
    - "error"
    - "declaration"
    - { allowArrowFunctions: true }
  no-unused-vars:
    - "warn"
    - { args: "none", ignoreRestSiblings: true }
  no-trailing-spaces:
    - "error"
  arrow-parens:
    - "error"
    - "always"
  eol-last:
    - "error"
    - "always"
  eqeqeq:
    - "error"
    - "allow-null"
  brace-style:
    - error
    - 1tbs
    - { allowSingleLine: true }
  block-spacing: 
    - error
    - always
  react/react-in-jsx-scope: 
    - off
  react/prop-types:
    - off

# .eslintrc.yml code inspired by expressjs/express github repository
# https://github.com/expressjs/express/blob/master/.eslintrc.yml