---
name: 🛠️ Refactoring
description: Refactoring your code to improve Open-Set-Go service!
title: "🛠️ [Refactor]: "
labels: ["refactor"]
assignees: []

body:
  - type: input
    id: location
    attributes:
      label: "Locations"
      description: Please tell me the location or part of the code you want to refactoring.
      placeholder: ex) src/pages
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Describe"
      description: A brief and clear description of the refactoring you are proposing.
    validations:
      required: true

    - type: textarea
    id: how-to
    attributes:
      label: "How to Improve Features"
      description: Describe how to improve the function.
    validations:
      required: false
