export const COLOR = {
  MAIN_WHITE: "#ffffff",
  MAIN_BLACK: "#050E04",
  MAIN_BACKGROUND: "#F4F4FC",
  MAIN_BLUE: "#2196F3",
  MAIN_HOVER: "#E3EEFA",
  MAIN_BORDER: "#C4C4CD",
  BORDER_GRAY: "#9696A3",
};
